### ISSUE TITLE
Don't know why it's not working

### ISSUE THREAD

**Issue by fr33s0ul** [s0md3v/Photon#111]
____  __          __
     / __ \/ /_  ____  / /_____  ____
    / /_/ / __ \/ __ \/ __/ __ \/ __ \
   / ____/ / / / /_/ / /_/ /_/ / / / /
  /_/   /_/ /_/\____/\__/\____/_/ /_/ v1.2.1

Traceback (most recent call last):
  File "photon.py", line 266, in <module>
    zap(main_url, args.archive, domain, host, internal, robots)
  File "/pentest/Photon/core/zap.py", line 23, in zap
    response = requests.get(inputUrl + '/robots.txt').text
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.xxxxxxxxxxxxxx.com', port=443): Max retries exceeded with url: /robots.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f343a97aad0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by dataexfiltration** [comment]
Use python3 photon.py and it should work
