### ISSUE TITLE
Issue Updating Photon

### ISSUE THREAD

**Issue by SolomonSklash** [s0md3v/Photon#125]
When updating Photon via `python3 photon.py --update`, I get the following error:
```
[~] Checking for updates
Traceback (most recent call last):
  File "photon.py", line 91, in <module>
    updater()
  File "/home/myuser/bounty/tools/Photon/core/updater.py", line 21, in updater
    changelog = changelog.group(1).split(';')
AttributeError: 'NoneType' object has no attribute 'group'
```

Using the latest updated Kali Linux: `Linux thinkpad 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux`
Python: `Python 3.7.3rc1`

**Comment by SolomonSklash** [comment]
I get the error still using the latest commit.

**Comment by danielr263** [comment]
I get the same error, but only whenever I try to run --dns
Traceback (most recent call last):
File "photon.py", line 414, in <module>
dnsdumpster(domain, output_dir)
File "/root/Photon/plugins/dnsdumpster.py", line 11 in dnsdumpster r"name='csrfmiddlewaretoken' value='(.*?)'', response).group(1) AttributeError: 'NoneType' object has no attribute 'group'
