### ISSUE TITLE
Issue Using the --headers Flag

### ISSUE THREAD

**Issue by SolomonSklash** [s0md3v/Photon#126]
When running the following Photon command, I receive an error:
`python3 photon.py -u example.com --headers`
This only happens when including the `--headers` flag.

```
Traceback (most recent call last):
  File "photon.py", line 138, in <module>
    headers = extract_headers(prompt())
  File "/home/myuser/bounty/tools/Photon/core/prompt.py", line 18, in prompt
    os.execvp(editor, [editor, tmpfile.name])
  File "/usr/lib/python3.7/os.py", line 571, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.7/os.py", line 613, in _execvpe
    raise last_exc
  File "/usr/lib/python3.7/os.py", line 604, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "photon.py", line 138, in <module>
    headers = extract_headers(prompt())
  File "/home/myuser/bounty/tools/Photon/core/prompt.py", line 22, in prompt
    return tmpfile.read().strip()
  File "/usr/lib/python3.7/tempfile.py", line 639, in __exit__
    self.close()
  File "/usr/lib/python3.7/tempfile.py", line 646, in close
    self._closer.close()
  File "/usr/lib/python3.7/tempfile.py", line 583, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpd56bth_3'
```

**Comment by s0md3v** [comment]
Are you on Windows?

**Comment by SolomonSklash** [comment]
Should have mentioned that. Latest Kali Linux.

`Linux thinkpad 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux`

`Python 3.7.3rc1`
