### ISSUE TITLE
A couple minor issues

### ISSUE THREAD

**Issue by Ekultek** [s0md3v/Photon#16]
# SSL issues

You're ignoring SSL verification:
```
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

You can fix this by adding the following to the top of the file (or wherever you feel like putting it):
```
import warnings
warnings.filterwarnings("ignore")
```

Now this is bad practice, for obvious reasons, however, it makes sense why you're doing it. The above solution is the quickest and simplest solution to solve the problem and keep the errors from being annoying.

An example with and without:

Without:
![without](https://user-images.githubusercontent.com/14183473/43142685-923f2350-8f1e-11e8-958c-013b9531e4e6.png)

With:
![with](https://user-images.githubusercontent.com/14183473/43142726-af8cfa18-8f1e-11e8-8242-2153894959af.png)

-----
# Dammit Unicode

If I supply a URL that is in, lets say Russian and try to extract all the data:

```
      ____  __          __
     / __ \/ /_  ____  / /_____  ____
    / /_/ / __ \/ __ \/ __/ __ \/ __ \
   / ____/ / / / /_/ / /_/ /_/ / / / /
  /_/   /_/ /_/\____/\__/\____/_/ /_/ 

 URLs retrieved from robots.txt: 5
 Level 1: 6 URLs
 Progress: 6/6
 Level 2: 35 URLs
 Progress: 35/35
 Level 3: 7 URLs
 Progress: 7/7
 Crawling 7 JavaScript files
 Progress: 7/7
Traceback (most recent call last):
  File "photon.py", line 429, in <module>
    f.write(x + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200b' in position 7: ordinal not in range(128)
```

Easiest solution would be to just ignore things like this and continue, with a warning to the user that it was ignored.

**Comment by s0md3v** [comment]
Can you please elaborate why ignoring SSL verification is a bad practice while crawling?

**Comment by s0md3v** [comment]
Why is it a bad practice? Do we even care if the website doesn't have a valid SSL certificate?
We just want to extract data from it.

**Comment by Ekultek** [comment]
`Now this is bad practice, for obvious reasons, however, _it makes sense why you're doing it._`

**Comment by s0md3v** [comment]
Alright.
About the encoding issue, can you please verify the patch?

**Comment by Ekultek** [comment]
Yeah give me one second

**Comment by Ekultek** [comment]
```
      ____  __          __
     / __ \/ /_  ____  / /_____  ____
    / /_/ / __ \/ __ \/ __/ __ \/ __ \
   / ____/ / / / /_/ / /_/ /_/ / / / /
  /_/   /_/ /_/\____/\__/\____/_/ /_/ 

 URLs retrieved from robots.txt: 5
 Level 1: 6 URLs
 Progress: 6/6
 Level 2: 39 URLs
 Progress: 39/39
 Crawling 7 JavaScript files
 Progress: 7/7
Traceback (most recent call last):
  File "photon.py", line 429, in <module>
    f.write(x + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200b' in position 7: ordinal not in range(128)

admin$ git log --name-status | head
commit b4481a7d08d0fde3e04b34db7f2b774a34d20902
Author: Somdev Sangwan <s0md3v@gmail.com>
Date:   Tue Jul 24 19:43:47 2018 +0530

    Encode strings to utf-8 while saving to file #16

M	photon.py

commit 73982e174629a1f8f44419049a71f25a4a782f69
Author: Somdev Sangwan <s0md3v@gmail.com>
```

**Comment by s0md3v** [comment]
Please re-clone and try again.
`f.write(x + '\n')` has been replaced by `f.write(str(x.encode('utf-8')) + '\n')`
