### ISSUE TITLE
Error Message while launching search after fresh installation

### ISSUE THREAD

**Issue by krish2001na** [s0md3v/Photon#168]
Hello There,
Can you help me with this error which i got while launching search after fresh installation
![image](https://user-images.githubusercontent.com/69446064/92301045-21a1b000-ef2e-11ea-9424-c601d2bde540.png)

also in text form below
      ____  __          __                                                                          
     / __ \/ /_  ____  / /_____  ____                                                               
    / /_/ / __ \/ __ \/ __/ __ \/ __ \                                                              
   / ____/ / / / /_/ / /_/ /_/ / / / /                                                              
  /_/   /_/ /_/\____/\__/\____/_/ /_/ v1.3.2                                                        

Traceback (most recent call last):
  File "photon.py", line 39, in <module>
    from core.utils import (luhn,
  File "/root/Photon/core/utils.py", line 7, in <module>
    import tld
ModuleNotFoundError: No module named 'tld'
Please help ASAP to enable me to use this wornderful program.
Thank you,

**Comment by akashkj** [comment]
How are you running it?

**Comment by picachuthefirst1** [comment]
I have this same error as well im using windows 10

**Comment by ServerHelp** [comment]
found the issue gotta do "pip install tld requests"

**Comment by Ayowel** [comment]
To avoid issues later and in other python projects, try to look at the requirements.txt file - it lists all required python libraries and can be used like this : `pip install -r requirements.txt` to install them

**Comment by sthagen** [comment]
Suggest to close this issue. As improvement maybe add a section close to the docker usage section explaining the basic native python use?
