### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'stream'

### ISSUE THREAD

**Issue by hktalent** [s0md3v/Photon#93]
```
py2 photon.py -u  http://xxxx/login.jsp --wayback
      ____  __          __
     / __ \/ /_  ____  / /_____  ____
    / /_/ / __ \/ __ \/ __/ __ \/ __ \
   / ____/ / / / /_/ / /_/ /_/ / / / /
  /_/   /_/ /_/\____/\__/\____/_/ /_/ v1.1.5

[~] Fetching URLs from archive.org
[+] Retrieved -1 URLs from archive.org
[~] Level 1: 1 URLs
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "photon.py", line 435, in extractor
    response = requester(url) # make request to the url
  File "photon.py", line 285, in requester
    return normal(url)
  File "photon.py", line 239, in normal
    response = get(url, cookies=cook, headers=finalHeaders, verify=False, timeout=timeout, stream=True)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/safe_mode.py", line 39, in wrapped
    return function(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 51, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'stream'
```

**Comment by s0md3v** [comment]
@hktalent You are using a really outdated version of the `requests` library which doesn't support the `stream` argument.
Update it and you will be fine.
